#!/bin/bash
#
# start-webserver
#

SELF_DIRNAME="`dirname -- "$0"`"
PROJECT_BASE_DIR="`cd -P -- "$SELF_DIRNAME" && pwd -P`"

cd $PROJECT_BASE_DIR/drupal
drush runserver --server=builtin 8088 --strict=0 </dev/null &>$HOME/server.log &
if [ $? != 0 ]
then
  echo "Could nt start php built-in webserver" >&2
  exit 1
fi
cd $PROJECT_BASE_DIR
