#!/bin/bash

# If a --uri= or @alias is needed for Drush calls,
# pass it in as the first (only) parameter to this script.
SITE_IDENTIFIER="$1"

SELF_DIRNAME="`dirname -- "$0"`"
PROJECT_BASE_DIR="`cd -P -- "$SELF_DIRNAME/.." && pwd -P`"
DRUPAL_ROOT="$PROJECT_BASE_DIR/drupal"

cd "$DRUPAL_ROOT"

# If there isn't a settings.local.php, create it and
# ensure that it bootstraps domain access.
if [ ! -f sites/default/settings.local.php ]
then
  echo "<?php" > sites/default/settings.local.php
fi
grep -q 'domain/settings.inc' sites/default/settings.local.php
if [ $? != 0 ]
then
  cat << __EOF__ >> sites/default/settings.local.php
// Include Domain access settings
try {
  include DRUPAL_ROOT . '/sites/all/modules/contrib/domain/settings.inc';
}
catch(Exception \$e) {}
__EOF__
fi

# Install the configuration settings form wk_config
drush "$SITE_IDENTIFIER" cb-umaster wk_config -y
